name: mockito
version: 5.4.6
description: >-
  A mock framework inspired by Mockito with APIs for Fakes, Mocks,
  behavior verification, and stubbing.
repository: https://github.com/dart-lang/mockito

topics:
 - testing
 - mocking

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: '>=7.4.1 <8.0.0'
  build: 3.0.2
  code_builder: ^4.5.0
  collection: ^1.19.0
  dart_style: '>=2.3.7 <4.0.0'
  matcher: ^0.12.16
  meta: ^1.15.0
  path: ^1.9.0
  source_gen: ">=3.1.0 <5.0.0"
  test_api: ">=0.6.1 <0.8.0"

dev_dependencies:
   lints: ^6.0.0
   build_runner: ^2.7.0
   build_test: ^3.3.2
   source_gen_test:
   test:
